### PR TITLE
Interfaces and logging added

### PR DESCRIPTION
**Pull request by MaksNevar**
Added interfaces IUnitOfWork and IRepository<T> with base implementations. Added logging for repository operations

### CODE REVIEW

**Comment by Elavrenov** [comment]
1. you have to create your own logger using inside ILogger from MS. Read about adapter& decorator patterns and chose one to implement.
2.Read about DI in ASP.NET CORE (files Program and Startup). You have to chose constructor ingestion for your purposes.
3.DB context have to be initialized in Startup.
4.getOne- > GetById , Remove(TEntity). we don't really need attach actions in Update method. Read about async programming in c#, naming conventions, TPL. Try to use Tasks<T> in your repo methods.
5. uow have to be async. uow realization have to be generic uow<TContext>. Try to look realization for generic uow (with methods GetRepository and RegisterRepository) 
6. rename itechart -> itechart.common
7. add new proj itechart.surveySite.repositories and move your buttonClicker logic here
8. completely change the entire logic in your controller

**Comment by Andrey-Ignatenko** [comment]
1. add _ReSharper.Caches to gitignore
2. logfile must not be commited to the repostiory
3. add ability to log exceptions
4. LogLevel - unused usings **code-styles**
5. iTechArt.Common - remove unused references/packages
6. IRepository - new line between methods **code-styles**
7. FindAsync - read about it. find out why it uses params.
8. Repository - reorder methods. **code-styles**
9. Repository - one new line between methods **code-styles**
10. Repository - log with debug level
11. _disposed - rename. _isDisposed. (is/has/was) **code-styles**
12. repo - rename. full name
13. `typeof(TEntity)` - to variable
14. notRegisteredRepository - rename. repository
15. `public virtual void Dispose(bool disposing)` - why public?
16. `if (_disposed) return;` -  **code-styles**
17. Repository  - remove whitespaces
18. RegisterRepositoryTypes - RegisterRepositoryType
19. TRepo - rename. full name.
20. ButtonClicksCounter - new line
21. ButtonClicksService - do not query DB in ctr
22. ButtonClickRepository.GetAllAsync - SingleOrDefaultAsync
23. ButtonClickRepository - add interface

**Comment by Andrey-Ignatenko** [comment]
1. repoType - rename (**again**)
2. GetRepository - refactoring. get rid of copy-paste
3. UnitOfWork - reorder members. same order as in interface. dispose - last
4. Do we need this line?
```
modelBuilder.Entity<ButtonClicksCounter>()
                .HasKey(buttonClicksCounter => buttonClicksCounter.Id);
```
5. `return (await GetAllAsync()).SingleOrDefault();` - do not query all. query single
6. ButtonClickRepository - query single item from db. do not query all.
7. Inject DbContext instead of ButtonClicksCounterDbContext
8. One line. If it fets on the screen, do not break a line.
```
            var currentClicksCounter = await
                GetButtonClicksAsync();
```
9. ButtonClicksService - do not create counter if it already exists
10. Seed initial counter when db is created
11. Do not nest method invocations `View(await _buttonClicksService.GetButtonClicksAsync());`
12. Create ViewModel (MVC) - do not use domain model `@model iTechArt.SurveysSite.DomainModel.ButtonClicksCounter`
13. `public async Task<IActionResult> ButtonClick()` - mark as POST
14. Mark increment with `[ValidateAntiForgeryToken]`

**Comment by Andrey-Ignatenko** [comment]
1. UnitOfWork - all fields should be private
2. ButtonClicksCounterDbContext - two new lines between ctr and methods **code-style**
```
                .HasData(new ButtonClicksCounter
                {
                    Id = 1,
                    Clicks = 0
                });
```
3. **code-style**
```
            var buttonClicks = new ButtonClicksCounterViewModel
            {
                Clicks = currentButtonClicksCounter.Clicks
            };
```
4. `return  await` - one whitespace
5. add logs to gitignore

**Comment by Andrey-Ignatenko** [comment]
1. Program - remove whitespaces, fix warnings.
2. ButtonClicksCounterDbContext - remove unused DbSet
3. Add R# annotations. Mark with UsedImplicitly where appropriate

**Comment by Andrey-Ignatenko** [comment]
1. Program - new line **code-styles**

**Pull request merged**
